[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
matplotlib = ">=3.1.1"
numpy = ">=1.17.2"
python = "^3.7"
scipy = ">=1.3.1"
tqdm = "^4.41"
